### ISSUE TITLE
Reducing R value

### ISSUE THREAD

**Issue by rustycandlewick** [wliusjtu/Robust-Color-Guided-Depth-Map-Restoration#3]
Hi,

Your ReadMe file mentions an r value which I should be able to change to reduce the memory necessary to run the program. I was wondering where this value was and how I might change it to properly run the code. Thanks!

**Comment by wliusjtu** [comment]
> Hi,
> 
> Your ReadMe file mentions an r value which I should be able to change to reduce the memory necessary to run the program. I was wondering where this value was and how I might change it to properly run the code. Thanks!

Many thanks for your interest in our paper. The r value refers to the variable 'rSmooth' in the 'Main.m' function.

In addition, we also have other code that performs depth map upsampling:
1. https://github.com/wliusjtu/Generalized-Smoothing-Framework  (TPAMI 2021)
2. https://github.com/wliusjtu/Semi-Global-Weighted-Least-Squares-in-Image-Filtering  (ICCV 2017)
please feel free to use these codes if they are useful to you.

**Comment by rustycandlewick** [comment]
I appreciate your help!
